app/translate_survey.py
See https://github.com/ONSdigital/eq-survey-runner/pull/1473
=> Update translation script now that groups are children of sections

app/extract_translation_data.py
=> Fix translation extract after section promotion

.travis.yml, Makefile
Added travis yaml and Makefile
=> Add travis and Makefile

app/extract_translation_data.py, app/translate_survey.py, tests/schemas/test_translation.json
- Added legal basis to translations
- https://github.com/ONSdigital/eq-survey-runner/pull/1748
=> Change legal basis

Makefile, Pipfile.lock, README.md, app/schema_translation.py, app/survey_schema.py, tests/schemas/test_translation.json, tests/test_survey_schema.py
Change the eq-translation app to work with the new piping and variants schemas.
=> Update eq-translations to work with new schema

.travis.yml, Dockerfile
We need to use eq-translations as part of runner tests.
Update the travis.yml to push to docker hub and modify to trigger on merge to v3.
=> Update travis to push to docker hub

.gitignore, .travis.yml, Dockerfile, Makefile, Pipfile, Pipfile.lock, README.md, app/schema_translation.py, app/survey_schema.py, app/utils.py, cli/compare_schemas.py, cli/extract_census_template.py, cli/template_extractor.py, cli/translate_all_surveys.py, cli/translate_census.py, cli/translate_survey.py, tests/schemas/test_translation.json, tests/test_pointers.py, tests/test_survey_schema.py
The V3 branch is not necessary - translations used by v2 of runner are currently using a tagged release number and the master branch is already using an older refactored POT version anyway.
=> Merge v3 to Master

.github/PULL_REQUEST_TEMPLATE.md, .pylintrc, .travis.yml, Makefile, Pipfile, Pipfile.lock, eq_translations/__init__.py, eq_translations/cli/compare_schemas.py, eq_translations/cli/extract_template.py, eq_translations/cli/translate_census.py, eq_translations/cli/translate_schema.py, eq_translations/entrypoints.py, eq_translations/schema_translation.py, eq_translations/survey_schema.py, eq_translations/utils.py, setup.py, tests/test_dumb_smart_quotes.py, tests/test_pointers.py, tests/test_schema_translation.py, tests/test_survey_schema.py
- Adds `black` to format the source consistently with our other repos.
- Updates the Pipfile lock and fixes some linting.
- Ensure extraction and translation still works as expected.
=> Add Black formatter & Update packages

eq_translations/__init__.py, setup.py
This adds version/release number that is checked in eq-questionnaire-schemas using `__version__` attribute. Simultaneously, new tagged eq-translations release with same version number(2.0.0) should be published.
After merge,[this PR](https://github.com/ONSdigital/eq-questionnaire-schemas/pull/30) should pass test-translation-templates GitHub Action check.
=> Add eq-translations version number

.github/workflows/pull_request.yml, Makefile
This removes failing pipenv check (API key error). The issue is described [here](https://github.com/pypa/pipenv/issues/2825). It puts eq-translations in line with our other repos.
=> Remove failing pipenv check

.github/workflows/pull_request.yml, Makefile
Updates the PR workflow action to use .python-version file. This will ensure the action is using the same version of Python we're using.
The action has also been updated to use the Makefile rather than duplicate the commands.
=> Update PR workflow action to use .python-version file

eq_translations/__init__.py
Updates the version to v3.0.0 ready for a release of the latest breaking changes.
=> Update version to v3.0.0

eq_translations/extractable_strings.py
Include content instructions in the set of extractable strings to be translated.
=> Add new content instruction key

eq_translations/__init__.py, eq_translations/extractable_strings.py
Add section repeat page_title to keys
=> Add Section repeating page_title

eq_translations/__init__.py, eq_translations/extractable_strings.py, tests/schemas/cy/test_language.json, tests/schemas/en/test_language.json, tests/schemas/ga/test_language.json, tests/schemas/test_language-cy.po, tests/schemas/test_language-ga.po, tests/schemas/test_language.pot
Describe what you have changed and why, link to other PRs or Issues as appropriate.
Describe the steps required to test the changes (include screenshots if appropriate).
=> Add definition to content

.github/workflows/pull_request.yml
Remove deprecated set-env commands from GitHub actions workflow files
Describe the steps required to test the changes (include screenshots if appropriate).
=> Remove deprecated set-env commands from GitHub Actions

eq_translations/__init__.py
Bumps the version number to v4.6.0 ready for release
=> Bump version number to v4.6.0

Pipfile.lock
This updates python packages, mainly adds version 1.26.6 of urllib3 to our Pipfile.lock.
Check if all tests and python scripts work as expected.
=> Update python package PRs

eq_translations/extractable_strings.py, tests/schemas/cy/test_language.json, tests/schemas/en/test_language.json, tests/schemas/test_language-cy.po, tests/schemas/test_language.pot
Adds the instruction field as an extractable string for answers
Check that instruction fields are extracted for translation
=> Add instruction to extractable strings

eq_translations/__init__.py, setup.py
=> Update to release v4.7.0

eq_translations/__init__.py
Small PR to update eq-translations version to the latest released version (v4.8.0).
Needed for v4.80 version of translations, check if I updated the __init__.py file to this version.
=> Update version to v4.8.0

.github/workflows/main.yml, README.md
Rename the default branch to main in the Github workflows
Github actions pass
=> Rename default branch to main

eq_translations/__init__.py
Small PR to update eq-translations version to the latest released version (v4.9.0).
Needed for v4.9.0 version of translations, check the change is to the correct version.
=> Update translations version to 4.9.0

eq_translations/__init__.py
Updates the eq-translations version to v4.9.1
Change makes sense
=> Update eq-translations version to v4.9.1

doc/decisions/0001-context-in-translations.md, tests/conftest.py, tests/test_survey_schema_extraction.py, tests/test_survey_schema_translation.py
After the breaking changes around highlighting that have gone into Runner and Author recently (https://github.com/ONSdigital/eq-questionnaire-runner/pull/1327) this needs replicating in other repos.
- Check that changes make sense in relation to the changes made in runner
- Tests pass
=> Update `em` tags to `strong`

eq_translations/extractable_strings.py, tests/test_schema_translation.py, tests/test_survey_schema_translation.py
Updated the extractable strings and added tests for content variants and repeating blocks.
- Check that the changes made make sense and nothing has been missed
- Check the tests pass
=> Add tests for content variants and repeating blocks

eq_translations/__init__.py
Updates the package version to 4.9.2
Tests pass
=> Update eq-translations to 4.9.2

eq_translations/__init__.py
Updates the package version to 4.10.2. 
Ensure the build passes and that you're able to run locally and with Docker.
=> Update eq-translations to 4.10.2
