requirements.txt, translations/test_translate_survey.py, translations/translate_survey.py
Adds accented characters to the regex for dumb to smart quote replacement. This fix means dumb quotes that follow an accented character are converted to the right kind of smart quote.
Once merged the Census Household schema can be regenerated to fix https://github.com/ONSdigital/eq-survey-runner/issues/774
=> Add accented characters to dumb quote replacement regex

scripts/run_translate_all_surveys.sh, scripts/run_translate_survey.sh, scripts/run_translation_extract.sh
Generating schemas will fail if there are spaces in the path.
1. Clone repository into a directory with spaces in `git clone https://github.com/ONSdigital/eq-translations.git eq\ translations`
1. Run  `./scripts/run_translate_all_surveys.sh $EQ_SURVEY_RUNNER_HOME/app/data`
=> Wrap with quotes to stop splitting

scripts/run_translate_all_surveys.sh
-  Changed source directory from "${path_to_schemas}"/ to "${path_to_schemas}"/en/...
- Related pull request https://github.com/ONSdigital/eq-survey-runner/pull/1105
- Checkout above pull request with updated directories
- Git clone eq-translations into directory
- cd into eq-translations and checkout 'eq-1059-moved-directory'
- Run ./scripts/run_translate_all_surveys.sh (and path-to-schemas [projects/eq-survey-runner/data) and check translations are working
=> modify translation directories

app/survey_schema.py, app/utils.py, tests/test_survey_schema.py
**Context**
The translation process currently updates placeholders to be a translated string, rather than a translated json structure. This means that the placeholder won't be resolved within a translated survey.
**Changes**
Update pointer search to ignore keys which contain placeholders and instead extract the text of them separately.
**To Test**
Run pytest and confirm the new unit tests pass.
=> Ensure placeholders do not update structure

README.md, app/survey_schema.py, tests/test_survey_schema.py
The [previous placeholder extraction](https://github.com/ONSdigital/eq-translations/pull/28) wrongly assumed that placeholders would never require context (i.e Be part of an answer). This change seeks to correct that. 
Instead of searching for placeholders using the 'text' key as part of a no_context key search, it searches for placeholders and filters them into separate lists dependant on whether they require context.
The new unit test (taken from census individual) includes keys that require both context and don't so should now cover both use cases. See if you agree with the approach.
=> Ensure placeholders with and without context are found correctly

app/utils.py, tests/test_survey_schema.py
In certain cases, the current pointer extraction yields the first pointer it finds for a dict, rather than searching through all possible pointers in its sub json structures.
Correct relevant tests to ensure all possible pointers are returned.
The amended test should fail in v3 and pass on the PR branch.
=> Fix pointer location

app/schema_translation.py, app/survey_schema.py, tests/test_survey_schema.py
Question Variant content is currently incorrectly translated - we are seeing this in census schemas as proxy content using non-proxy translations in the Welsh survey translation.
There's been a couple of discussions about how this should be done, but this is the solution I've used to prepare what has been supplied to Welsh Gov thus far. 
The user context is supplied to translate messages. A deepcopy of the schema is now used as we were overwriting the original schema object.
=> Correct proxy content

.gitignore, Pipfile, Pipfile.lock, cli/translate_census.py
To translate a census schema includes a number of steps and requires navigating the crowdin site ui. It would be useful to have a script which could be used to translate as part of an automated process.
Add a crowdin translation script, which interacts with the crowdin api to fetch the translation file and use it for translation of a schema.
=> Add a Census Crowdin Translation Script

app/utils.py, cli/compare_schemas.py, cli/translate_survey.py, tests/test_pointers.py
It is currently very difficult to identify structural differences in a schema. It requires a manual process of stepping through two large json structures and checking to see if we can see differences amongst content changes.
This means checking whether a translation process has done anything other than modify text is very time consuming.
Add methods that list/compare all pointers within a schema and use them during translation to warn of differences.
=> Add a script for Comparing Schemas

README.md, cli/extract_census_template.py, cli/template_extractor.py, cli/translate_all_surveys.py, cli/translate_census.py
Extracting the census individual schema involves extracting from both the different regions versions of the census, concatenating the templates together and uploading to crowdin. As a manual process, it is easy to make a mistake.
Create a script which extracts the census_individual.pot in a single step, taking a runner data/en folder as an argument.
=> Extract Census Script

eq_translations/survey_schema.py, setup.py, tests/test_survey_schema.py
The relationship collector's `playback` key and the summary `item_title` key were not being properly translated.
I don't think either of these keys require context. 
The `item_title` key is currently supported when using placeholders, but validator does allow you to use a plain string, which wouldn't currently be supported.
=> Add playback and item_title pointer extraction

eq_translations/entrypoints.py, eq_translations/survey_schema.py, tests/test_survey_schema.py
New keys have been introduced as part of https://github.com/ONSdigital/eq-survey-runner/pull/2293 and https://github.com/ONSdigital/eq-schema-validator/pull/151 which are visible in section summaries and need to be translated.
=> Add list collector keys used on Section Summary

eq_translations/survey_schema.py, tests/test_survey_schema.py
The current Census schema contains `when` rules with a `list` property that specifies which list the rule applies to. This element was being incorrectly being extracted as content to be translated, leading to warnings when translating schemas. Valid warnings are at risk of being ignored while these erroneous ones remain. 
- Run `pipenv run python -m eq_translations.cli.extract_template ../eq-survey-runner/data/en/census_household_gb_eng.json` and check that single character strings (`h`,`o`,`u`,`s`,`e`,`h`,`o`,`l`,`d`) don't appear in the generated pot file.
=> Fix broken extraction when list element is a string

.gitignore, eq_translations/cli/compare_schemas.py, eq_translations/cli/extract_template.py, eq_translations/cli/translate_census.py, eq_translations/cli/translate_schema.py, eq_translations/schema_translation.py, eq_translations/survey_schema.py, eq_translations/utils.py, tests/test_schema_translation.py
**Motivation**
Some answers are not being translated when answer translations exist in the translation (.po) file. This is due to some answers where multiple answer ids are listed for a single translation. Or translation currently assumes there is only a single answer id.
**Changes**
Update the answer search to assume context contains a list of answer_ids. Additionally, don't show translation warnings about empty strings.
=> Fix answers not being translated

eq_translations/survey_schema.py, tests/test_survey_schema.py
New key has been introduced as part of https://github.com/ONSdigital/eq-survey-runner/pull/2449 and https://github.com/ONSdigital/eq-schema-validator/pull/168 which are visible in questions and need to be translated.
To run tests:
```
make test
```
To manually test if new key is being translated the following command can be run: 
Extract translatable text from an eQ schema with
```
pipenv run python -m eq_translations.cli.extract_template <schema_file> <output_directory>
```
Check if new "instruction" templates are added to generated .pot file
=> Add instruction key used on CCS

eq_translations/utils.py, tests/test_dumb_smart_quotes.py
Adding the dumb quote check to the eq-schema-validator has highlighted an issue with this repo. Dumb double quotes were not being replaced when running 'make translate'. I have added additional regex statements to search and replace the dumb double quotes.
We need to make this change before we add the new method to validator so that our build will not fail(see the validator PR [here](https://github.com/ONSdigital/eq-schema-validator/pull/166)).
Update the eq-translations branch in runner, run 'make build' and check that the translated strings that previously contained double quotes are updated with smart quotes
=> Add regex to replace dumb double quotes

eq_translations/survey_schema.py
This has PR has been opened to add action_text key to eq_translations. This is required to support the PR raised for eq-questionnaire-runner [here](https://github.com/ONSdigital/eq-questionnaire-runner/pull/13).
=> Adding the action_text key

eq_translations/survey_schema.py, eq_translations/utils.py, tests/test_survey_schema.py
This adds support for translations and tests of multiple items on a list. Previously, placeholders were not used in lists of contents(despite existing rules in validator) and methods were expecting only strings to be passed during translation process and checks.
The change is described on this trello [card](https://trello.com/c/d8k4s5QA) and requires this
[schema PR](https://github.com/ONSdigital/eq-questionnaire-schemas/pull/19) to be merged.
=> Remove hard coded census date

doc/decisions/0001-context-in-translations.md
For some translatable strings we create a message context (`msgctxt`) that contains the question text. This enables strings to be translated in the context of the question being asked. There are two current issues with this approach:
- For some elements the context is incorrect. For example, the context for an answer guidance title is "Answer for: {question_text}".
- Most translatable strings at the question level and below don't have context. This causes problems when the English text doesn't vary between question variants but the translated text needs to - https://trello.com/c/JEdbgtlT/3538-e-translations-add-context-to-all-child-elements-of-a-question-m
This pull request proposes some changes to fix these issues and make translating a questionnaire easier.
=> Document translatable strings and context

eq_translations/__init__.py, eq_translations/extractable_strings.py, tests/schemas/cy/test_language.json, tests/schemas/en/test_language.json, tests/schemas/test_language-cy.po, tests/schemas/test_language.pot
Adds the new `warning` question property.
Verify that the extraction and translation of the property works. The property has been added to the `test_language` questionnaire for this purpose.
=> Add question warning property

eq_translations/__init__.py, eq_translations/extractable_strings.py, tests/schemas/cy/test_language.json, tests/schemas/en/test_language.json, tests/schemas/en/test_translation.json, tests/schemas/test_language-cy.po, tests/schemas/test_language.pot
Updating the extractable string for question descriptions to be comprised of a list of strings. Required for https://trello.com/c/On5OBCNm/3939-add-line-break-functionality-in-question-description-m
Confirm that the translate-able string has be updated as expected and schemas and translation templates match.
=> Add line break functionality to instruction and description

tests/test_survey_schema_translation.py
This adds test for schema .pot file translations and extraction of translatable items when there is empty("null") label present in answers.
Run `make test`, run extract and translate of checkbox schema with empty label.
=> Add schema translations test for null answer label

eq_translations/__init__.py, eq_translations/extractable_strings.py, tests/schemas/cy/test_language.json, tests/schemas/en/test_language.json, tests/schemas/ga/test_language.json, tests/schemas/test_language-cy.po, tests/schemas/test_language-ga.po, tests/schemas/test_language.pot
Added translation support for `placeholder` introduced by https://github.com/ONSdigital/eq-questionnaire-validator/pull/82
Ensure extraction and translation for `placeholder` works with not side effects.
=> Support translation of placeholder text in dropdown answers

eq_translations/extractable_strings.py, tests/schemas/cy/test_language.json, tests/schemas/en/test_language.json, tests/schemas/test_language-cy.po, tests/schemas/test_language.pot
Adds the new post submission guidance properties to translations.
Check that the post submission guidance strings are extracted and regeneration of a translated schema contains the strings.
=> Translate post submission guidance contents

eq_translations/__init__.py, setup.py
Poetry fails to install this package due to version not being found. Currently it is imported statement which is causing the issue. Version no is now explicitly mentioned in setuptools.py so poetry can pick it up.
companion [Validator PR](https://github.com/ONSdigital/eq-questionnaire-validator/pull/136) 
Check if poetry ( in validator) is able to install this package using branch name
_eq-translations = {git = "https://github.com/ONSDigital/eq-translations.git", rev = "update-setup-to-support-poetry"}_
=> Update setup to support poetry

.github/workflows/pull_request.yml
Dependabot creates branches with "/" which Docker tags deems invalid, causing dependabot pull requests to fail at docker push.
Added `CLEAN_TAG` bash command from `eq-questionaire-runner` to transform "/" to  "-" letting the docker tag to be valid.
Run Docker Push action with a dependabot repo or a repo with "/"
=> Update docker tag step in pull_requests.yml

eq_translations/__init__.py, setup.py
Updates the way we import of version in `setup.py` as setup is not in scope when we are using eq-translations as a package on other repos.
Check that the version is resolved as expected.
=> Update import of version in setup.py

eq_translations/extractable_strings.py, tests/test_survey_schema_extraction.py
Adds introduction block to translatable strings, some context added for the less obvious elements like question preview description.
You need to run extract script followed by translate schema one. Best if you create .po file from generate .pot file and do translations manually to test.
=> Add introduction schema element to translatable items list 

eq_translations/extractable_strings.py, tests/test_survey_schema_extraction.py
Adds the new summary field `item_label` to the extractable strings list. Needed to support [iteration 1 of looping](https://github.com/ONSdigital/eq-questionnaire-validator/pull/153)
Describe the steps required to test the changes (include screenshots if appropriate).
=> Add item_label to extractable summary strings
